Feature/3
Navarayha/ios-corgi-club-app pull request #8
Opened 2022-09-17 08:48 UTC by mi1212

промежуточно подготовлен LoginViewController, CreateUserViewController, FakeAuthService

2022-09-18 10:43 UTC, afirthes requested changes

2022-09-18 10:43 UTC, afirthes commented on Features/Common/Sources/UserModel.swift
> +public struct UserCorgi: Identifiable, Codable {
Правильно что переименовываешь класс. Ты добавил постфикс "Corgi" чтобы идентифицировать принадлежность к нашему приложению. Предлагают все же отличать классы префиксами, вроде CС или лучше Corgi Club, т.е. CCUser.
Не забудь поправить название файла соотвественно.

2022-09-18 10:43 UTC, afirthes commented on Features/CreateUserUI/Sources/CreateUserViewController.swift
> +//  Copyright © 2022 Sonomos.com. All rights reserved.
Это не наша фирма :)

2022-09-18 10:43 UTC, afirthes commented on Features/FirebaseAuthService/Sources/FirebaseAuthService.swift
> +        Firebse
Не скомпилится.

2022-09-18 10:43 UTC, afirthes commented on Features/HomeCoordinator/Sources/HomeCoordinator.swift
> +            /* необходимо перенести выше
Здесь оставь, но на будущее - отсутсвие "мусорных" комментов с кодом - плохой стиль.

2022-09-19 10:57 UTC, closed without merging

2022-09-19 10:59 UTC, mi1212 commented on Features/CreateUserUI/Sources/CreateUserViewController.swift
> +//  Copyright © 2022 Sonomos.com. All rights reserved.
Это кстати tuist везде добавляет, идентификаторы всех проектов начинаются с com.sonomos